#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routes.yaml
swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui

register:
  path: /register
  controller: App\Controller\RegisterController::register
  methods: POST

login_check:
  path: /login_check

reset-password:
  path: /users/{id}/reset-password

