#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routes.yaml
api_login_check:
    path: /api/login_check
    methods: ['POST']
swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui
authentication_token:
    path: /authentication_token
    methods: ['POST']
