#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routes.yaml
swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui
api_login_check:
    path: /api/login_check
reset-password:
    path: /users/{id}/reset-password

