App\Entity\Ressource:
    attributes:
        security: 'is_granted("ROLE_USER")'
    collectionOperations:
        post:
            method: 'POST'
            security: 'is_granted("ROLE_ADMIN")'
            security_message: 'Only admins can add books.'
    itemOperations:
        get:
            method: 'GET'
            security: 'is_granted("ROLE_USER") and object.owner == user'
            security_message: 'Sorry, but you are not the book owner.'
        put:
            method: 'PUT'
            security_post_denormalize: "is_granted('ROLE_ADMIN') or (object.owner == user and previous_object.owner == user)"
            security_post_denormalize_message: 'Sorry, but you are not the actual book owner.'